/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intersystems.ensemble;
import org.eclipse.milo.opcua.stack.core.types.builtin.DataValue;

public class DataValueResult {

    private String nodeName;
    private String statusCode;
    private String value;
    private Long sourceTime;
    private Long serverTime;

    public DataValueResult(DataValue dv,String nodeName){
        if (dv.getStatusCode().isGood()) {
            this.statusCode="good";
        } else if (dv.getStatusCode().isBad()) {
            this.statusCode="bad";
        } else if (dv.getStatusCode().isUncertain()) {
            this.statusCode="uncertain";
        } else {
            this.statusCode="unknown";
        }
        this.value=dv.getValue().getValue().toString();
        this.sourceTime=new Long(dv.getSourceTime().getUtcTime());
        this.serverTime=new Long(dv.getServerTime().getUtcTime());
        this.nodeName=nodeName;
    }

    public String getNodeName() {
        return this.nodeName;
    }

    public String getStatusCode() {
        return this.statusCode;
    }
    public String getValue() {
        return this.value;
    }
    public Long getSourceTime() {
        return this.sourceTime;
    }
    public Long getServerTime() {
        return this.serverTime;
    }
}
